/* Emit a textual LLVM module for one immutable CHIP-8 ROM.
   The module owns the control-flow graph.  The runtime owns VM state and I/O. */
#include <errno.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "chip8.h"

static void die(const char *message)
{
  fprintf(stderr, "chip8-aot: %s\n", message);
  exit(1);
}

static void emit_block(FILE *out, unsigned pc, uint16_t op, unsigned last)
{
  fprintf(out, "pc%03x:\n", pc);
  fprintf(out, "  %%stop%03x = call i32 @chip8_aot_execute(i16 %u)\n", pc, (unsigned)op);
  fprintf(out, "  %%done%03x = icmp ne i32 %%stop%03x, 0\n", pc, pc);
  fprintf(out, "  br i1 %%done%03x, label %%exit, label %%dispatch\n\n", pc);
  (void)last;
}

int main(int argc, char **argv)
{
  const char *input = NULL;
  const char *output = NULL;
  FILE *in;
  FILE *out;
  uint8_t rom[MEMORY_SIZE - ENTRYPOINT];
  size_t size;

  if (argc != 4 || strcmp(argv[2], "-o") != 0)
    {
      fprintf(stderr, "Usage: %s ROM -o OUTPUT.ll\n", argv[0]);
      return 1;
    }
  input = argv[1];
  output = argv[3];
  in = fopen(input, "rb");
  if (in == NULL) die(strerror(errno));
  size = fread(rom, 1, sizeof(rom), in);
  if (ferror(in)) die("cannot read ROM");
  if (fgetc(in) != EOF) die("ROM is larger than the CHIP-8 program area");
  fclose(in);
  if (size == 0 || (size & 1)) die("ROM size must be a nonzero even number");

  out = fopen(output, "w");
  if (out == NULL) die(strerror(errno));
  fprintf(out, "; Generated by chip8-aot from %s.\n", input);
  fprintf(out, "; The ROM is immutable.  chip8_aot_execute verifies each embedded opcode.\n\n");
  fprintf(out, "declare i32 @chip8_aot_execute(i16)\n");
  fprintf(out, "declare i16 @chip8_aot_program_counter()\n\n");
  fprintf(out, "@chip8_aot_rom = constant [%zu x i8] [", size);
  for (size_t i = 0; i < size; ++i)
    fprintf(out, "%si8 %u", i == 0 ? "" : ", ", (unsigned)rom[i]);
  fprintf(out, "]\n@chip8_aot_rom_size = constant i32 %zu\n\n", size);
  fprintf(out, "define void @chip8_aot_run() {\nentry:\n  br label %%dispatch\n\ndispatch:\n");
  fprintf(out, "  %%pc = call i16 @chip8_aot_program_counter()\n");
  fprintf(out, "  switch i16 %%pc, label %%exit [\n");
  for (size_t i = 0; i < size; i += 2)
    fprintf(out, "    i16 %u, label %%pc%03x\n", (unsigned)(ENTRYPOINT + i), (unsigned)(ENTRYPOINT + i));
  fprintf(out, "  ]\n\n");
  for (size_t i = 0; i < size; i += 2)
    emit_block(out, ENTRYPOINT + (unsigned)i, (uint16_t)((rom[i] << 8) | rom[i + 1]), (unsigned)(i + 2 == size));
  fprintf(out, "exit:\n  ret void\n}\n");
  if (fclose(out) != 0) die("cannot write LLVM IR");
  return 0;
}
